### ISSUE TITLE
Banned words use regular expressions

### ISSUE THREAD

**Issue by icecoldfire** [Blue9/AudioJack#4]
You can make your banned words filter better with regular expressions.

For 320kbps you can use this: `[0-9]*[\s]?kbp[s]?`.
For 1080p and 720p you can use this: `[0-9]*p`.

**Comment by Blue9** [comment]
Thanks for your suggestions. I will promptly commit the first suggestion.

As for your second suggestion, the regular expression could remove more than just video quality terms. For example, if a song title contains "100p", "12:00pm", or something similar, the regex will affect the title even though it may be valid. Therefore, I think it is best to just enter the video qualities manually.
