### ISSUE TITLE
[request] youtube-dl playlist support

### ISSUE THREAD

**Issue by wlilley93** [Blue9/AudioJack#6]
Hi,

This is absolutely fantastic work, thank you for creating this. One of the great features of youtube-dl is the ability to download playlists one video after another, but I notice in your py file that you comment you haven't had chance to add this yet. I was just wondering if this was still something you envisage adding in?

Many thanks!

**Comment by Blue9** [comment]
Yes, I plan on adding playlist support in the near future. 😃
